- name: Copying over clo-namespace.yaml
  template:
    src: templates/clo-namespace.yaml.j2
    dest:  "{{ target_dir }}clo-namespace.yaml"
    owner: "{{ template_owner }}"
    group: "{{ template_owner }}"
    mode: 0666

- name: Copying over clo-og.yaml
  template:
    src: templates/clo-og.yaml.j2
    dest:  "{{ target_dir }}clo-og.yaml"
    owner: "{{ template_owner }}"
    group: "{{ template_owner }}"
    mode: 0666

- name: Copying over clo-sub.yaml
  template:
    src: templates/clo-sub.yaml.j2
    dest:  "{{ target_dir }}clo-sub.yaml"
    owner: "{{ template_owner }}"
    group: "{{ template_owner }}"
    mode: 0666


- name: Creating the openshift-logging Namespace using oc-cli
  command: "oc create -f {{ target_dir }}clo-namespace.yaml"
  when: not  delete_deployment | bool and not use_ansible_k8s | bool

- name: Creating the Cluster Logging Operator using oc-cli
  command: "oc create -f {{ target_dir }}clo-og.yaml"
  when: not  delete_deployment | bool and not use_ansible_k8s | bool

- name: Creating the Cluster Logging Subscription object using oc-cli
  command: "oc create -f {{ target_dir }}clo-sub.yaml"
  when: not  delete_deployment | bool and not use_ansible_k8s | bool

- name: Waiting for  Cluster Logging Operator to Succeeded using oc-cli
  shell: |
    set -o pipefail && /usr/local/bin/oc get csv --all-namespaces -n openshift-logging | grep "openshift-logging"
  register: install_status
  until: "'Succeeded' in install_status.stdout"
  when: not  delete_deployment | bool and not use_ansible_k8s | bool
  retries: 60
  delay: 15
  args:
    executable: /bin/bash

- name: Creating the openshift-logging Namespace k8s
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - "{{ target_dir }}clo-namespace.yaml"
  - "{{ target_dir }}clo-og.yaml"
  - "{{ target_dir }}clo-sub.yaml"
  when: not  delete_deployment | bool and use_ansible_k8s | bool

- name: Wait for clusterlogging CRD to be ready
  k8s_info:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: clusterloggings.logging.openshift.io
  register: r_logging_crd
  retries: 200
  delay: 10
  until: r_logging_crd.resources | list | length == 1
  when: not  delete_deployment | bool and use_ansible_k8s | bool

- name: wait for cluster-logging-operator to be ready
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: openshift-logging
    label_selectors:
      - name = cluster-logging-operator
    field_selectors:
      - status.phase=Running
  register: r_logging_pod
  retries: 120
  delay: 10
  until: r_logging_pod.resources | list | length == 1
  when: not  delete_deployment | bool and use_ansible_k8s | bool

- name: Deleting the Cluster Logging Operator
  command: "oc delete -f {{ target_dir }}clo-og.yaml"
  when:  delete_deployment | bool and not use_ansible_k8s | bool
  ignore_errors: yes

- name: Deleting the Cluster Logging Subscription object
  command: "oc delete -f {{ target_dir }}clo-sub.yaml"
  when:  delete_deployment | bool and not use_ansible_k8s | bool
  ignore_errors: yes

- name: Deleting the openshift-logging Namespace
  command: "oc delete -f {{ target_dir }}clo-namespace.yaml"
  when:  delete_deployment | bool and not use_ansible_k8s | bool
  ignore_errors: yes

- name: Removing the openshift-logging Namespace k8s
  k8s:
    state: absent
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - "{{ target_dir }}clo-namespace.yaml"
  - "{{ target_dir }}clo-og.yaml"
  - "{{ target_dir }}clo-sub.yaml"
  when:  delete_deployment | bool and use_ansible_k8s | bool
  ignore_errors: yes